
package cn.ebatech.imixpark.user.webService_fj;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "n_frdif", targetNamespace = "http://tempurl.org", wsdlLocation = "http://222.178.70.44:5000/frdif/n_frdif.asmx?WSDL")
public class NFrdif
    extends Service
{

    private final static URL NFRDIF_WSDL_LOCATION;
    private final static WebServiceException NFRDIF_EXCEPTION;
    private final static QName NFRDIF_QNAME = new QName("http://tempurl.org", "n_frdif");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://222.178.70.44:5000/frdif/n_frdif.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFRDIF_WSDL_LOCATION = url;
        NFRDIF_EXCEPTION = e;
    }

    public NFrdif() {
        super(__getWsdlLocation(), NFRDIF_QNAME);
    }

    public NFrdif(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFRDIF_QNAME, features);
    }

    public NFrdif(URL wsdlLocation) {
        super(wsdlLocation, NFRDIF_QNAME);
    }

    public NFrdif(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFRDIF_QNAME, features);
    }

    public NFrdif(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NFrdif(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NFrdifSoap
     */
    @WebEndpoint(name = "n_frdifSoap")
    public NFrdifSoap getNFrdifSoap() {
        return super.getPort(new QName("http://tempurl.org", "n_frdifSoap"), NFrdifSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NFrdifSoap
     */
    @WebEndpoint(name = "n_frdifSoap")
    public NFrdifSoap getNFrdifSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempurl.org", "n_frdifSoap"), NFrdifSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFRDIF_EXCEPTION!= null) {
            throw NFRDIF_EXCEPTION;
        }
        return NFRDIF_WSDL_LOCATION;
    }

}
